name: Generate Datas

on:
  schedule: # Executa a cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch: # Permite execução manual

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest

    steps:
      # Configurar usuário Git para evitar problemas de push
      - name: Configurar usuário Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"

      # Criar diretório dist se não existir
      - name: Criar diretório dist
        run: mkdir -p dist

      # Gerar animação Snake
      - name: Gerar animação Snake
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: NaeLL22
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Publicar no GitHub Pages
      - name: Publicar no GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
